# ------ root_path/dataset_name ------
root_path: '/home/ce/data'

seed: 3407

# ------ Hyperparamters ------
search_hp: True

search_scale: [0, 0, 0, 0, 0.3]
search_scale2: [20, 5, 0, 0, 0.9]
search_step: [200, 20, 1, 1, 10]

init_beta: 6
init_alpha: 1.5
init_beta2: 0
init_alpha2: 0
init_lambda: 0.75

eps: 0.001
training_feat_num: 1024
training_free_feat_num: 1024

w_training_free: [0.9, 0.1]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'eurosat'
backbone: 'RN50'

lr: 0.0001 # 0.001
augment_epoch: 10
train_epoch: 200
