# ------ root_path/dataset_name ------
root_path: '/home/ce/data'

seed: 3407
## We use the seed 3407 for all experiments following APE.
## The seed 3407 comes from the paper:
##    ''Torch.manual_seed(3407) is all you need: 
##      On the influence of random seeds in deep learning architectures for computer vision''

# ------ Hyperparamters ------
search_hp: True

search_scale: [0, 0, 0, 0, 0.6] 
search_scale2: [4, 4, 5, 4, 0.9]
search_step: [200, 40, 1, 1, 20]


init_beta: 2
init_alpha: 1.2
init_beta2: 0
init_alpha2: 0
init_lambda: 0.75

eps: 0.001
training_feat_num: 1024 # RN50: 1024, others: 512
training_free_feat_num: 1024 # RN50: 1024, others: 512

w_training_free: [0.7, 0.3]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'imagenet'
backbone: 'RN50'

lr: 0.0001
augment_epoch: 20
train_epoch: 20
