# ------ root_path/dataset_name ------
root_path: '/home/ce/data'

seed: 3407

# ------ Hyperparamters ------
search_hp: True

search_scale: [15, 7, 0.2, 0.2]
search_step: [100, 20, 10, 10]

init_beta: 1
init_alpha: 1
init_beta2: 0
init_alpha2: 0
init_lambda: 0.75

eps: 0.002
training_feat_num: 1024
training_free_feat_num: 1024

w_training_free: [0.3, 0.7]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'ucf101'
backbone: 'RN50'

lr: 0.0001
augment_epoch: 10
train_epoch: 30
